-- MySQL Script generated by MySQL Workbench
-- Mon Apr 12 20:06:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `clientUserName` VARCHAR(45) NOT NULL,
  `clientPass` VARCHAR(45) NOT NULL,
  `clientFName` VARCHAR(45) NOT NULL,
  `clientMInt` VARCHAR(1) NULL,
  `clientLName` VARCHAR(45) NOT NULL,
  `clientEmail` VARCHAR(45) NULL,
  `clientAddress` VARCHAR(45) NULL,
  `clientHomePhone` INT NULL,
  `clientCellPhone` INT NULL,
  PRIMARY KEY (`clientUserName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lawyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lawyer` (
  `lawyerUserName` VARCHAR(45) NOT NULL,
  `lawyerPass` VARCHAR(45) NOT NULL,
  `lawyerFName` VARCHAR(45) NOT NULL,
  `lawyerMInt` VARCHAR(1) NULL,
  `lawyerLName` VARCHAR(45) NOT NULL,
  `lawyerEmail` VARCHAR(45) NULL,
  `lawyerAddress` VARCHAR(45) NULL,
  `lawyerHomePhone` INT NULL,
  `lawyerCellPhone` INT NULL,
  PRIMARY KEY (`lawyerUserName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointments` (
  `idAppointments` INT NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `clientUserName` VARCHAR(45) NULL,
  `employeeUserName` VARCHAR(45) NULL,
  `addNotes` MEDIUMTEXT NULL,
  `status` VARCHAR(15) NULL,
  PRIMARY KEY (`idAppointments`),
  INDEX `clientUserName_idx` (`clientUserName` ASC) VISIBLE,
  INDEX `employeeUserName_idx` (`employeeUserName` ASC) VISIBLE,
  CONSTRAINT `clientUserName`
    FOREIGN KEY (`clientUserName`)
    REFERENCES `mydb`.`Client` (`clientUserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lawyerUserName`
    FOREIGN KEY (`employeeUserName`)
    REFERENCES `mydb`.`Lawyer` (`lawyerUserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Case Loads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Case Loads` (
  `employeeUserName` VARCHAR(45) NOT NULL,
  `casesWon` INT NULL,
  `casesLost` INT NULL,
  PRIMARY KEY (`employeeUserName`),
  CONSTRAINT `employeeUserName`
    FOREIGN KEY (`employeeUserName`)
    REFERENCES `mydb`.`Lawyer` (`lawyerUserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Senior Partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Senior Partner` (
  `seniorUserName` VARCHAR(45) NOT NULL,
  `seniorPass` VARCHAR(45) NOT NULL,
  `seniorEmail` VARCHAR(45) NULL,
  `seniorFName` VARCHAR(45) NOT NULL,
  `seniorMInt` VARCHAR(1) NULL,
  `seniorLName` VARCHAR(45) NOT NULL,
  `seniorAddress` VARCHAR(45) NULL,
  `seniorHomePhone` INT NULL,
  `seniorCellPhone` INT NULL,
  PRIMARY KEY (`seniorUserName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `adminUserName` VARCHAR(45) NOT NULL,
  `adminPass` VARCHAR(45) NOT NULL,
  `adminEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`adminUserName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fees` (
  `appointmentID` INT NOT NULL,
  `billing` VARCHAR(45) NULL,
  PRIMARY KEY (`appointmentID`),
  CONSTRAINT `idAppointments`
    FOREIGN KEY (`appointmentID`)
    REFERENCES `mydb`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employeeUserName` VARCHAR(45) NOT NULL,
  `employeePass` VARCHAR(45) NOT NULL,
  `employeeFName` VARCHAR(45) NOT NULL,
  `employeeMInt` VARCHAR(1) NULL,
  `employeeLName` VARCHAR(45) NOT NULL,
  `employeeEmail` VARCHAR(45) NULL,
  `employeeAddress` VARCHAR(45) NULL,
  `employeeHomePhone` INT NULL,
  `employeeCellPhone` INT NULL,
  `employeeAssignedLawyer` VARCHAR(45) NULL,
  PRIMARY KEY (`employeeUserName`),
  INDEX `employeeAssignedLawyer_idx` (`employeeAssignedLawyer` ASC) VISIBLE,
  CONSTRAINT `employeeAssignedLawyer`
    FOREIGN KEY (`employeeAssignedLawyer`)
    REFERENCES `mydb`.`Lawyer` (`lawyerUserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `mydb`.`admin` (adminUserName, adminPass)
VALUES ("admin", "test");



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into `employee` values('JoeTest','123456','Joe','I','G','1@1','12Walnut');

select `employeeUserName` from `employee`;
